### ISSUE TITLE
Create Travis CI and AppVeyor configuration

### ISSUE THREAD

**Issue by luigiberrettini** [EasyNetQ/docker-rabbitmq#2]
Take a note of the user and password of the Docker Hub account created to close #1

Add this repository on Travis CI and set these environment variables (in Settings):
 - DOCKER_USER  (display value in build log turned off)
 - DOCKER_PASS (display value in build log turned off)

Add a project on AppVeyor and encrypt the value of the Docker Hub user and password writing the encrypted value in a comment to this issue

I will submit a PR that will allow to build and push Docker images based on the encrypted credentials

**Comment by micdenny** [comment]
@luigiberrettini I've added you as admin on AppVeyor

about travis ci, need to investigate on it

**Comment by micdenny** [comment]
about travis ci, you should see the repo on your personal account, now I've connected it and the build works.
